//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTCM.Infrastructure.Common.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoTCM.Infrastructure.Common.Message.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Id do cliente é obrigatório.
        /// </summary>
        public static string Client_ClientID_Required {
            get {
                return ResourceManager.GetString("Client_ClientID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF já foi utilizado para outro vendedor.
        /// </summary>
        public static string Client_CPF_Duplicate {
            get {
                return ResourceManager.GetString("Client_CPF_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatório.
        /// </summary>
        public static string Client_CPF_Required {
            get {
                return ResourceManager.GetString("Client_CPF_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data é obrigatório.
        /// </summary>
        public static string Client_Date_Required {
            get {
                return ResourceManager.GetString("Client_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail já foi utilizado para outro vendedor.
        /// </summary>
        public static string Client_Email_Duplicate {
            get {
                return ResourceManager.GetString("Client_Email_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        public static string Client_Name_Required {
            get {
                return ResourceManager.GetString("Client_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo pagamento é obrigatório.
        /// </summary>
        public static string Client_Payment_Required {
            get {
                return ResourceManager.GetString("Client_Payment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Id do vendedor é obrigatório.
        /// </summary>
        public static string Client_SalesmanID_Required {
            get {
                return ResourceManager.GetString("Client_SalesmanID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string MsgBoxTitleError {
            get {
                return ResourceManager.GetString("MsgBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        public static string MsgBoxTitleSuccess {
            get {
                return ResourceManager.GetString("MsgBoxTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string MsgBoxTitleWarning {
            get {
                return ResourceManager.GetString("MsgBoxTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo código externo já foi utilizado para outro produto.
        /// </summary>
        public static string Product_ExternalCode_Duplicate {
            get {
                return ResourceManager.GetString("Product_ExternalCode_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo codigo do produto é obrigatório.
        /// </summary>
        public static string Product_ExternalCode_Required {
            get {
                return ResourceManager.GetString("Product_ExternalCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome do produto é obrigatório.
        /// </summary>
        public static string product_Name_Required {
            get {
                return ResourceManager.GetString("product_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo valor unitário é obrigatório.
        /// </summary>
        public static string product_UnitPrice_Required {
            get {
                return ResourceManager.GetString("product_UnitPrice_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CNPJ já foi utilizado para outro usuário.
        /// </summary>
        public static string Provider_CNPJ_Duplicate {
            get {
                return ResourceManager.GetString("Provider_CNPJ_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CNPJ é obrigatório.
        /// </summary>
        public static string Provider_CNPJ_Required {
            get {
                return ResourceManager.GetString("Provider_CNPJ_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail já foi utilizado para outro vendedor.
        /// </summary>
        public static string Provider_Email_Duplicate {
            get {
                return ResourceManager.GetString("Provider_Email_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo Nome é obrigatório.
        /// </summary>
        public static string Provider_Name_Required {
            get {
                return ResourceManager.GetString("Provider_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sale_Payment_Duplicate {
            get {
                return ResourceManager.GetString("Sale_Payment_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Quantidade é obrigatório.
        /// </summary>
        public static string SaleProduct_Quantity_Required {
            get {
                return ResourceManager.GetString("SaleProduct_Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo endereço é obrigatório.
        /// </summary>
        public static string Salesman_Address_Required {
            get {
                return ResourceManager.GetString("Salesman_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF já foi utilizado para outro vendedor.
        /// </summary>
        public static string Salesman_CPF_Duplicate {
            get {
                return ResourceManager.GetString("Salesman_CPF_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatório.
        /// </summary>
        public static string Salesman_CPF_Required {
            get {
                return ResourceManager.GetString("Salesman_CPF_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail já foi utilizado para outro vendedor.
        /// </summary>
        public static string Salesman_Email_Duplicate {
            get {
                return ResourceManager.GetString("Salesman_Email_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail é obrigatório.
        /// </summary>
        public static string Salesman_Email_Required {
            get {
                return ResourceManager.GetString("Salesman_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        public static string Salesman_Name_Required {
            get {
                return ResourceManager.GetString("Salesman_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo telefone é obrigatório.
        /// </summary>
        public static string Salesman_Phone_Required {
            get {
                return ResourceManager.GetString("Salesman_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo quantidade é obrigatório.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado, por favor contato o administrador..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou senha inválidos.
        /// </summary>
        public static string User_Athentication_Invalid {
            get {
                return ResourceManager.GetString("User_Athentication_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja bem vindo!.
        /// </summary>
        public static string User_Athentication_Welcome {
            get {
                return ResourceManager.GetString("User_Athentication_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado o id para exclusão.
        /// </summary>
        public static string User_Delete_Error_ID {
            get {
                return ResourceManager.GetString("User_Delete_Error_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail já foi utilizado para outro usuário.
        /// </summary>
        public static string User_Email_Duplicate {
            get {
                return ResourceManager.GetString("User_Email_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail é obrigatório.
        /// </summary>
        public static string User_Email_Required {
            get {
                return ResourceManager.GetString("User_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo login já foi utilizado para outro usuário.
        /// </summary>
        public static string User_Login_Duplicate {
            get {
                return ResourceManager.GetString("User_Login_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo login é obrigatório.
        /// </summary>
        public static string User_Login_Required {
            get {
                return ResourceManager.GetString("User_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome é obrigatório.
        /// </summary>
        public static string User_Name_Required {
            get {
                return ResourceManager.GetString("User_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo senha é obrigatório.
        /// </summary>
        public static string User_Password_Required {
            get {
                return ResourceManager.GetString("User_Password_Required", resourceCulture);
            }
        }
    }
}
